### ISSUE TITLE
cpu/gpu device issue 

### ISSUE THREAD

**Issue by georgosgeorgos** [GT4SD/gt4sd-core#144]
**Describe the bug**

Mismatch CPU/GPU device

**Run with GPU:**

```
gt4sd-trainer  --training_pipeline_name paccmann-vae-trainer --epochs 250 --batch_size 4 --n_layers 1 --rnn_cell_size 16 --latent_dim 16 --train_smiles_filepath src/gt4sd/training_pipelines/tests/molecules.smi --test_smiles_filepath src/gt4sd/training_pipelines/tests/molecules.smi --model_path /tmp/gt4sd-paccmann-gp/ --training_name fast-example --eval_interval 15 --save_interval 15 --selfies
```

**Error:** 

```
ERROR:gt4sd.training_pipelines.paccmann.vae.core:Exception occurred while running PaccMannVAETrainingPipeline
Traceback (most recent call last):
  File "/dccstor/nccr-cat/pwd/envs/gt4sd/lib/python3.7/site-packages/gt4sd/training_pipelines/paccmann/vae/core.py", line 247, in train
    batch_mode=params["batch_mode"],
  File "/dccstor/nccr-cat/pwd/envs/gt4sd/lib/python3.7/site-packages/paccmann_chemistry/models/training.py", line 143, in train_vae
    device=device
  File "/dccstor/nccr-cat/pwd/envs/gt4sd/lib/python3.7/site-packages/paccmann_chemistry/models/training.py", line 346, in _prepare_padded
    end_index=end_index
  File "/dccstor/nccr-cat/pwd/envs/gt4sd/lib/python3.7/site-packages/paccmann_chemistry/utils/utils.py", line 74, in sequential_data_preparation
    decoder_batch[dropout_loc] = dropout_indices
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
04:48:05   Exception occurred while running PaccMannVAETrainingPipeline
Traceback (most recent call last):
  File "/dccstor/nccr-cat/pwd/envs/gt4sd/lib/python3.7/site-packages/gt4sd/training_pipelines/paccmann/vae/core.py", line 247, in train
    batch_mode=params["batch_mode"],
  File "/dccstor/nccr-cat/pwd/envs/gt4sd/lib/python3.7/site-packages/paccmann_chemistry/models/training.py", line 143, in train_vae
    device=device
  File "/dccstor/nccr-cat/pwd/envs/gt4sd/lib/python3.7/site-packages/paccmann_chemistry/models/training.py", line 346, in _prepare_padded
    end_index=end_index
  File "/dccstor/nccr-cat/pwd/envs/gt4sd/lib/python3.7/site-packages/paccmann_chemistry/utils/utils.py", line 74, in sequential_data_preparation
    decoder_batch[dropout_loc] = dropout_indices
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Fatal error condition occurred in /opt/vcpkg/buildtrees/aws-c-io/src/9e6648842a-364b708815.clean/source/event_loop.c:72: aws_thread_launch(&cleanup_thread, s_event_loop_destroy_async_thread_fn, el_group, &thread_options) == AWS_OP_SUCCESS
Exiting Application
```

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - GT4SD version: 0.50

**Comment by drugilsberg** [comment]
Interesting, do you think it's something related to the implementation of that specific trainer, or is it something that needs to be addressed at the level of the PaccMann dependencies?

**Comment by georgosgeorgos** [comment]
Not sure. I'm looking into it.

**Comment by georgosgeorgos** [comment]
https://github.com/PaccMann/paccmann_chemistry/pull/18
