### ISSUE TITLE
Problem multiprocess in requirements

### ISSUE THREAD

**Issue by georgosgeorgos** [GT4SD/gt4sd-core#92]
The new multiprocess library version (`0.70.13`) gives problems when installing `gt4sd-core` using the development mode. I had to set `multiprocess==0.70.12.2` to install the library.

**Comment by drugilsberg** [comment]
Thanks for reporting.
Here it would be great to have a stack/error trace to understand what errors exactly.
I tried a build both on Ubuntu and Mac OS X and it went through without pinning the requirements.

**Comment by georgosgeorgos** [comment]
Installing in development mode `pip install --no-deps -e .` we have a problem related to the `wheel` version:

gt4sd-core git:(main) ✗ gt4sd-inference --algorithm_name PaccMannRL --algorithm_application PaccMannRLProteinBasedGenerator --target MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTT --number_of_samples 10

Traceback (most recent call last):
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.20.1 (/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages), Requirement.parse('protobuf<3.20,>=3.9.2'), {'tensorboard'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/gt4sd_tmp/bin/gt4sd-inference", line 33, in <module>
    sys.exit(load_entry_point('gt4sd', 'console_scripts', 'gt4sd-inference')())
  File "/opt/anaconda3/envs/gt4sd_tmp/bin/gt4sd-inference", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ggi/_otehr/gt4sd-core/src/gt4sd/cli/inference.py", line 35, in <module>
    from ..algorithms.registry import ApplicationsRegistry
  File "/Users/ggi/_otehr/gt4sd-core/src/gt4sd/algorithms/__init__.py", line 28, in <module>
    from .conditional_generation.guacamol.core import (  # noqa: F401
  File "/Users/ggi/_otehr/gt4sd-core/src/gt4sd/algorithms/conditional_generation/guacamol/__init__.py", line 26, in <module>
    from .core import (
  File "/Users/ggi/_otehr/gt4sd-core/src/gt4sd/algorithms/conditional_generation/guacamol/core.py", line 28, in <module>
    from ....training_pipelines.core import TrainingPipelineArguments
  File "/Users/ggi/_otehr/gt4sd-core/src/gt4sd/training_pipelines/__init__.py", line 30, in <module>
    import pkg_resources
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3246, in <module>
    @_call_aside
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/anaconda3/envs/gt4sd_tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel>=0.26' distribution was not found and is required by tensorboard

**Comment by georgosgeorgos** [comment]
Setting `pip install wheel==0.26` and `pip install protobuf==3.9.2` we can run inference.

**Comment by drugilsberg** [comment]
> Setting `pip install wheel==0.26` and `pip install protobuf==3.9.2` we can run inference.

Probably here, it's just about:

- changing the `<=` to a `<` in [this line](https://github.com/GT4SD/gt4sd-core/blob/1ab31092b1117cd3ff9578c55334efbc5ca0428f/requirements.txt#L24)
- adding `wheel>=0.26` in `requirements.txt`
